apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipelineiq-api
  namespace: pipelineiq
  labels:
    app: pipelineiq-api
    version: "3.0.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pipelineiq-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: pipelineiq-api
      annotations:
        rollme: "initial"
    spec:
      serviceAccountName: pipelineiq-sa
      initContainers:
        - name: migrate
          image: ghcr.io/siddharthk17/pipelineiq-backend:latest
          imagePullPolicy: Always
          command: ["alembic", "upgrade", "head"]
          workingDir: /app
          envFrom:
            - configMapRef:
                name: pipelineiq-config
            - secretRef:
                name: pipelineiq-secrets
      containers:
        - name: api
          image: ghcr.io/siddharthk17/pipelineiq-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: http
          envFrom:
            - configMapRef:
                name: pipelineiq-config
            - secretRef:
                name: pipelineiq-secrets
          env:
            - name: OTEL_SERVICE_NAME
              value: pipelineiq-api
          livenessProbe:
            httpGet:
              path: /livez
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: pipelineiq-api
  namespace: pipelineiq
spec:
  selector:
    app: pipelineiq-api
  ports:
    - port: 80
      targetPort: 8000
      name: http
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pipelineiq-api-hpa
  namespace: pipelineiq
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pipelineiq-api
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipelineiq-sa
  namespace: pipelineiq
