services:
  - type: web
    name: pipelineiq-api
    runtime: docker
    region: singapore
    plan: free
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: APP_VERSION
        value: "3.6.2"
      - key: UPLOAD_DIR
        value: /tmp/uploads
      - key: FIRST_SUPERUSER_EMAIL
        value: admin@pipelineiq.app
      - key: FIRST_SUPERUSER_PASSWORD
        sync: false
      - key: CORS_ORIGINS
        value: '["https://pipelineiq.vercel.app","https://pipelineiq-api.onrender.com","https://frontend-zeta-blue-67.vercel.app"]'
    healthCheckPath: /health
