"""add schema snapshots and pipeline versions

Revision ID: 14a9b359a361
Revises: 97385cb62e0a
Create Date: 2026-03-03 18:54:58.266400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14a9b359a361'
down_revision: Union[str, None] = '97385cb62e0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
