"""add_severity_to_contracts

Revision ID: 1a158ef49016
Revises: f9a1b2c3d4e5
Create Date: 2026-05-22 16:51:35.403800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a158ef49016'
down_revision: Union[str, None] = 'f9a1b2c3d4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_asset_rel_source', table_name='asset_relationships')
    op.drop_index('idx_asset_rel_source_pipeline', table_name='asset_relationships')
    op.drop_index('idx_asset_rel_target', table_name='asset_relationships')
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('contract_violations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_data_assets_name_trgm', table_name='data_assets', postgresql_using='gin')
    op.drop_index('idx_data_assets_owner', table_name='data_assets')
    op.drop_index('idx_data_assets_type', table_name='data_assets')
    op.drop_index('idx_file_profiles_file_id', table_name='file_profiles')
    op.create_unique_constraint(None, 'file_profiles', ['file_id'])
    op.alter_column('healing_attempts', 'old_schema',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('healing_attempts', 'new_schema',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('healing_attempts', 'removed_columns',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('healing_attempts', 'added_columns',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('healing_attempts', 'renamed_candidates',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('healing_attempts', 'gemini_patch',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('healing_attempts', 'sandbox_result',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('healing_attempts', 'diff_lines',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('healing_attempts', 'validation_errors',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('healing_attempts', 'validation_warnings',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index('ix_healing_attempts_applied', table_name='healing_attempts')
    op.drop_constraint('uq_healing_attempts_run_attempt', 'healing_attempts', type_='unique')
    op.drop_index('idx_lineage_graphs_run_id', table_name='lineage_graphs')
    op.alter_column('notification_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('pipeline_contracts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('pipeline_contracts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('pipeline_permissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('pipeline_permissions_pipeline_name_user_id_key', 'pipeline_permissions', type_='unique')
    op.alter_column('pipeline_runs', 'trigger',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'manual'::character varying"))
    op.drop_index('idx_pipeline_runs_pipeline_name', table_name='pipeline_runs')
    op.drop_index('idx_pipeline_runs_user_created', table_name='pipeline_runs')
    op.alter_column('pipeline_schedules', 'pipeline_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('pipeline_schedules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('pipeline_schedules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_pipeline_schedules_active', table_name='pipeline_schedules', postgresql_where='(is_active = true)')
    op.drop_index('idx_pipeline_schedules_user', table_name='pipeline_schedules')
    op.drop_index('idx_schedule_runs_schedule_id', table_name='schedule_runs')
    op.drop_index('idx_step_results_run_id', table_name='step_results')
    op.alter_column('uploaded_files', 'file_size_bytes',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.drop_index('ix_uploaded_files_original_filename', table_name='uploaded_files')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.alter_column('webhook_deliveries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('webhooks', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('webhooks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('webhooks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('webhooks', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('webhook_deliveries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_uploaded_files_original_filename', 'uploaded_files', ['original_filename'], unique=False)
    op.alter_column('uploaded_files', 'file_size_bytes',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.create_index('idx_step_results_run_id', 'step_results', ['pipeline_run_id', 'step_index'], unique=False)
    op.create_index('idx_schedule_runs_schedule_id', 'schedule_runs', ['schedule_id', 'triggered_at'], unique=False)
    op.create_index('idx_pipeline_schedules_user', 'pipeline_schedules', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_pipeline_schedules_active', 'pipeline_schedules', ['is_active', 'next_run_at'], unique=False, postgresql_where='(is_active = true)')
    op.alter_column('pipeline_schedules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('pipeline_schedules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('pipeline_schedules', 'pipeline_name',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.create_index('idx_pipeline_runs_user_created', 'pipeline_runs', ['user_id', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_pipeline_runs_pipeline_name', 'pipeline_runs', ['name', sa.text('created_at DESC')], unique=False)
    op.alter_column('pipeline_runs', 'trigger',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'manual'::character varying"))
    op.create_unique_constraint('pipeline_permissions_pipeline_name_user_id_key', 'pipeline_permissions', ['pipeline_name', 'user_id'])
    op.alter_column('pipeline_permissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('pipeline_contracts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('pipeline_contracts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notification_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('idx_lineage_graphs_run_id', 'lineage_graphs', ['pipeline_run_id'], unique=False)
    op.create_unique_constraint('uq_healing_attempts_run_attempt', 'healing_attempts', ['pipeline_run_id', 'attempt_number'])
    op.create_index('ix_healing_attempts_applied', 'healing_attempts', ['applied'], unique=False)
    op.alter_column('healing_attempts', 'validation_warnings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('healing_attempts', 'validation_errors',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('healing_attempts', 'diff_lines',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('healing_attempts', 'sandbox_result',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('healing_attempts', 'gemini_patch',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('healing_attempts', 'renamed_candidates',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('healing_attempts', 'added_columns',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('healing_attempts', 'removed_columns',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('healing_attempts', 'new_schema',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('healing_attempts', 'old_schema',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint(None, 'file_profiles', type_='unique')
    op.create_index('idx_file_profiles_file_id', 'file_profiles', ['file_id'], unique=True)
    op.create_index('idx_data_assets_type', 'data_assets', ['asset_type'], unique=False)
    op.create_index('idx_data_assets_owner', 'data_assets', ['owner_id'], unique=False)
    op.create_index('idx_data_assets_name_trgm', 'data_assets', ['name'], unique=False, postgresql_using='gin')
    op.alter_column('contract_violations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('idx_asset_rel_target', 'asset_relationships', ['target_id'], unique=False)
    op.create_index('idx_asset_rel_source_pipeline', 'asset_relationships', ['source_id', 'pipeline_name'], unique=False)
    op.create_index('idx_asset_rel_source', 'asset_relationships', ['source_id'], unique=False)
    # ### end Alembic commands ###
