"""add_user_id_to_uploaded_files

Revision ID: cb3e11c88344
Revises: 0009
Create Date: 2026-04-06 09:53:00.476632

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cb3e11c88344"
down_revision: Union[str, None] = "0009"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add user_id as nullable first to handle existing data
    op.add_column("uploaded_files", sa.Column("user_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        None, "uploaded_files", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )

    # Assign existing files to the first available user
    connection = op.get_bind()
    user_id_res = connection.execute(sa.text("SELECT id FROM users LIMIT 1")).fetchone()
    if user_id_res:
        user_id = user_id_res[0]
        connection.execute(
            sa.text(
                "UPDATE uploaded_files SET user_id = :user_id WHERE user_id IS NULL"
            ),
            {"user_id": user_id},
        )

    # Now set to nullable=False
    op.alter_column("uploaded_files", "user_id", nullable=False)


def downgrade() -> None:
    op.drop_constraint(None, "uploaded_files", type_="foreignkey")
    op.drop_column("uploaded_files", "user_id")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "webhooks",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "webhooks",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.create_index(
        "ix_webhook_deliveries_webhook_id",
        "webhook_deliveries",
        ["webhook_id"],
        unique=False,
    )
    op.create_index(
        "ix_webhook_deliveries_run_id", "webhook_deliveries", ["run_id"], unique=False
    )
    op.alter_column(
        "webhook_deliveries",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.create_index("ix_users_username", "users", ["username"], unique=False)
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_index("ix_users_email", "users", ["email"], unique=False)
    op.create_unique_constraint("users_username_key", "users", ["username"])
    op.create_unique_constraint("users_email_key", "users", ["email"])
    op.alter_column(
        "users",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint(None, "uploaded_files", type_="foreignkey")
    op.alter_column(
        "uploaded_files",
        "file_size_bytes",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.drop_column("uploaded_files", "user_id")
    op.create_index(
        "ix_step_results_pipeline_run_id_step_index",
        "step_results",
        ["pipeline_run_id", "step_index"],
        unique=False,
    )
    op.create_index(
        "ix_step_results_pipeline_run_id",
        "step_results",
        ["pipeline_run_id"],
        unique=False,
    )
    op.alter_column(
        "pipeline_schedules",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.create_index(
        "ix_pipeline_runs_user_id_created_at",
        "pipeline_runs",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_pipeline_runs_status", "pipeline_runs", ["status"], unique=False
    )
    op.create_index(
        "ix_pipeline_runs_created_at", "pipeline_runs", ["created_at"], unique=False
    )
    op.create_unique_constraint(
        "pipeline_permissions_pipeline_name_user_id_key",
        "pipeline_permissions",
        ["pipeline_name", "user_id"],
    )
    op.alter_column(
        "pipeline_permissions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "notification_configs",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint(None, "file_profiles", type_="unique")
    op.create_index(
        "idx_file_profiles_file_id", "file_profiles", ["file_id"], unique=True
    )
    op.create_index(
        "ix_audit_logs_user_id_created_at",
        "audit_logs",
        ["user_id", "created_at"],
        unique=False,
    )
    op.alter_column(
        "audit_logs",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###
