apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-critical
  namespace: pipelineiq
  labels:
    app: worker-critical
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-critical
  template:
    metadata:
      labels:
        app: worker-critical
    spec:
      containers:
        - name: worker
          image: ghcr.io/siddharthk17/pipelineiq-backend:latest
          imagePullPolicy: Always
          command:
            - celery
            - -A
            - backend.celery_app
            - worker
            - --queues=critical
            - --concurrency=2
            - --prefetch-multiplier=1
            - --hostname=critical@%(h)s
            - --loglevel=info
          workingDir: /app
          envFrom:
            - configMapRef:
                name: pipelineiq-config
            - secretRef:
                name: pipelineiq-secrets
          env:
            - name: OTEL_SERVICE_NAME
              value: pipelineiq-worker-critical
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "500m"
