import { describe, test, expect } from 'vitest'
import * as Y from 'yjs'

describe('Yjs CRDT: basic document operations', () => {
  test('two documents merge correctly after concurrent edits', () => {
    const docA = new Y.Doc()
    const docB = new Y.Doc()

    const nodesA = docA.getMap<Record<string, unknown>>('nodes')
    const nodesB = docB.getMap<Record<string, unknown>>('nodes')

    const nodeA = {
      id: 'load_data', type: 'stepNode', position: { x: 100, y: 100 },
      data: { type: 'load', name: 'load_data', config: {} }
    }
    docA.transact(() => nodesA.set('load_data', nodeA))

    const nodeB = {
      id: 'filter_rows', type: 'stepNode', position: { x: 400, y: 100 },
      data: { type: 'filter', name: 'filter_rows', config: {} }
    }
    docB.transact(() => nodesB.set('filter_rows', nodeB))

    const updateA = Y.encodeStateAsUpdate(docA)
    const updateB = Y.encodeStateAsUpdate(docB)
    Y.applyUpdate(docA, updateB)
    Y.applyUpdate(docB, updateA)

    expect(nodesA.size).toBe(2)
    expect(nodesB.size).toBe(2)
    expect(nodesA.has('load_data')).toBe(true)
    expect(nodesA.has('filter_rows')).toBe(true)
  })

  test('Y.Text concurrent edits merge without data loss', () => {
    const docA = new Y.Doc()
    const docB = new Y.Doc()

    const textA = docA.getText('yaml')
    const textB = docB.getText('yaml')

    textA.insert(0, 'pipeline:\n  name: test\n')

    const initUpdate = Y.encodeStateAsUpdate(docA)
    Y.applyUpdate(docB, initUpdate)

    textA.insert(textA.length, '  steps:\n')
    textB.insert(0, '# Generated by AI\n')

    Y.applyUpdate(docA, Y.encodeStateAsUpdate(docB))
    Y.applyUpdate(docB, Y.encodeStateAsUpdate(docA))

    const resultA = textA.toString()
    expect(resultA).toContain('# Generated by AI')
    expect(resultA).toContain('pipeline:')
    expect(resultA).toContain('steps:')
  })

  test('observer fires when remote node is added', () => {
    const docA = new Y.Doc()
    const docB = new Y.Doc()
    const nodesA = docA.getMap<Record<string, unknown>>('nodes')
    const nodesB = docB.getMap<Record<string, unknown>>('nodes')

    let observerFiredCount = 0
    nodesA.observe(() => { observerFiredCount++ })

    docB.transact(() => nodesB.set('new_step', { id: 'new_step', type: 'stepNode', position: {x:0,y:0}, data: {} }))

    Y.applyUpdate(docA, Y.encodeStateAsUpdate(docB))

    expect(observerFiredCount).toBe(1)
    expect(nodesA.has('new_step')).toBe(true)
  })

  test('yNodes.set does not lose existing nodes', () => {
    const doc = new Y.Doc()
    const yNodes = doc.getMap<Record<string, unknown>>('nodes')

    doc.transact(() => {
      yNodes.set('a', { id: 'a', data: {} })
      yNodes.set('b', { id: 'b', data: {} })
    })

    const existing = Array.from(yNodes.entries())
    doc.transact(() => {
      yNodes.clear()
      existing.forEach(([k, v]) => {
        if (k === 'a') yNodes.set(k, { ...(v as Record<string, unknown>), position: { x: 999, y: 999 } })
        else yNodes.set(k, v)
      })
    })

    expect(yNodes.size).toBe(2)
    expect(yNodes.get('b')).toBeDefined()
  })

  test('node position update propagates to other document', () => {
    const docA = new Y.Doc()
    const docB = new Y.Doc()
    const nodesA = docA.getMap<Record<string, unknown>>('nodes')
    const nodesB = docB.getMap<Record<string, unknown>>('nodes')

    const initial = { id: 'step1', position: { x: 100, y: 100 }, data: {} }
    docA.transact(() => nodesA.set('step1', initial as unknown as Record<string, unknown>))
    Y.applyUpdate(docB, Y.encodeStateAsUpdate(docA))

    docA.transact(() => nodesA.set('step1', { ...initial, position: { x: 500, y: 300 } }))
    Y.applyUpdate(docB, Y.encodeStateAsUpdate(docA))

    const nodeOnB = nodesB.get('step1') as Record<string, unknown> | undefined
    expect((nodeOnB?.position as Record<string, number>)?.x).toBe(500)
    expect((nodeOnB?.position as Record<string, number>)?.y).toBe(300)
  })

  test('deletion propagates to other document', () => {
    const docA = new Y.Doc()
    const docB = new Y.Doc()
    const nodesA = docA.getMap<Record<string, unknown>>('nodes')
    const nodesB = docB.getMap<Record<string, unknown>>('nodes')

    docA.transact(() => {
      nodesA.set('keep', { id: 'keep', data: {} })
      nodesA.set('delete_me', { id: 'delete_me', data: {} })
    })
    Y.applyUpdate(docB, Y.encodeStateAsUpdate(docA))

    docA.transact(() => nodesA.delete('delete_me'))
    Y.applyUpdate(docB, Y.encodeStateAsUpdate(docA))

    expect(nodesB.has('delete_me')).toBe(false)
    expect(nodesB.has('keep')).toBe(true)
  })
})
